---
- name: Tags example
  hosts: all 
  tasks:
    - name: Tag Name - beta 
      ansible.builtin.debug:
        msg: "Execution tag - Beta"
      tags: [never, beta] 
      when: inventory_hostname in groups['dev']
      changed_when: true

    - name: Tag Name - alpha 
      ansible.builtin.debug:
        msg: "Execution tag - alpha"
      tags: [never, alpha]
      when: inventory_hostname in groups['dev']
      changed_when: true
