galaxy_info:
  author: Student User
  description: A role to ensure deployment of HAProxy
  company: Example, Inc.
  license: BSD
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies:
  - name: firewall
