---
ansible-navigator:
 execution-environment:
   container-engine: podman
   enabled: true
   image: aap.lab.example.com/ee-supported-rhel8:latest
   pull:
     policy: missing
 playbook-artifact:
   enable: false
